// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_dotnet.Data;

#nullable disable

namespace backend_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920152907_AddTargetDomainAndJobTitleReferences")]
    partial class AddTargetDomainAndJobTitleReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_dotnet.Models.Application", b =>
                {
                    b.Property<Guid>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("InterviewTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SummaryReport")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("AppId");

                    b.HasIndex("JobId");

                    b.HasIndex("StudentId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("backend_dotnet.Models.CompanyProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessRegistrationDocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPersonEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.ToTable("CompanyProfiles");
                });

            modelBuilder.Entity("backend_dotnet.Models.CompanyStaffProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("JobPosition")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyStaffProfiles");
                });

            modelBuilder.Entity("backend_dotnet.Models.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int[]>("AllowedYearsOfStudy")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("integer");

                    b.Property<string[]>("InternshipType")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("JobDescriptionSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("JobTitleId")
                        .HasColumnType("integer");

                    b.Property<string>("LocationCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("MandatorySkills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("MinimumGPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string[]>("NiceToHaveSkills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("PreferredDegreePrograms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("StipendAmountOrDetails")
                        .HasColumnType("text");

                    b.Property<bool>("StipendOffered")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetDomain")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("TargetDomainId")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("TargetDomainId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("backend_dotnet.Models.JobTitleReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TargetDomainId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TargetDomainId");

                    b.HasIndex("Title", "TargetDomainId")
                        .IsUnique();

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("backend_dotnet.Models.StudentProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CampusIdPhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CareerObjectivesSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentYearOfStudy")
                        .HasColumnType("integer");

                    b.Property<string>("CvPdfUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DegreeProgram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DesiredJobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpectedGraduationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("GPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string[]>("InternshipType")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("LectureScheduleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("text");

                    b.Property<string[]>("PreferredLocations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PrimaryDomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("ToolsAndTechnologies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("backend_dotnet.Models.TargetDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TargetDomains");
                });

            modelBuilder.Entity("backend_dotnet.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend_dotnet.Models.Application", b =>
                {
                    b.HasOne("backend_dotnet.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.User", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("backend_dotnet.Models.CompanyProfile", b =>
                {
                    b.HasOne("backend_dotnet.Models.User", "User")
                        .WithOne("CompanyProfile")
                        .HasForeignKey("backend_dotnet.Models.CompanyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_dotnet.Models.CompanyStaffProfile", b =>
                {
                    b.HasOne("backend_dotnet.Models.CompanyProfile", "Company")
                        .WithMany("StaffMembers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.User", "User")
                        .WithOne("CompanyStaffProfile")
                        .HasForeignKey("backend_dotnet.Models.CompanyStaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_dotnet.Models.Job", b =>
                {
                    b.HasOne("backend_dotnet.Models.CompanyProfile", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.JobTitleReference", "JobTitleReference")
                        .WithMany("Jobs")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend_dotnet.Models.TargetDomain", "DomainReference")
                        .WithMany("Jobs")
                        .HasForeignKey("TargetDomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("DomainReference");

                    b.Navigation("JobTitleReference");
                });

            modelBuilder.Entity("backend_dotnet.Models.JobTitleReference", b =>
                {
                    b.HasOne("backend_dotnet.Models.TargetDomain", "TargetDomain")
                        .WithMany("JobTitles")
                        .HasForeignKey("TargetDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetDomain");
                });

            modelBuilder.Entity("backend_dotnet.Models.StudentProfile", b =>
                {
                    b.HasOne("backend_dotnet.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("backend_dotnet.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_dotnet.Models.CompanyProfile", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("backend_dotnet.Models.Job", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("backend_dotnet.Models.JobTitleReference", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("backend_dotnet.Models.TargetDomain", b =>
                {
                    b.Navigation("JobTitles");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("backend_dotnet.Models.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CompanyProfile");

                    b.Navigation("CompanyStaffProfile");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
