import type { CompanyDashboardData } from '../types/company';

const API_BASE = 'http://localhost:5168/api';

const DEFAULT_DASHBOARD_DATA: CompanyDashboardData = {
  companyId: 'vir-default-1',
  companyName: 'Virtusa Corporation',
  industry: 'Information Technology & Digital Engineering',
  contactPersonName: 'Virtusa Campus Recruitment',
  contactPersonEmail: 'virtusa@company.com',
  phone: '+1 (555) 482-1920',
  orgCode: 'VIR-8821',
  stats: {
    activeJobDrives: 4,
    prescreenedStudents: 186,
    interviewsScheduled: 24,
    partnerUniversityReach: 34,
  },
  activeJobs: [
    {
      jobId: 'job-01',
      jobTitle: 'Backend Engineering Co-op',
      targetDomain: 'Distributed Systems & APIs • 6 Months',
      jobDescriptionSummary: 'Build and scale high-throughput cloud microservices.',
      internshipType: ['Full-time', 'Hybrid'],
      locationCity: 'San Jose, CA',
      minimumGPA: 3.5,
      allowedYearsOfStudy: [3, 4],
      mandatorySkills: ['Python', 'Go', 'PostgreSQL'],
      niceToHaveSkills: ['Docker', 'Kubernetes'],
      preferredDegreePrograms: ['B.S. Computer Science'],
      stipendOffered: true,
      stipendAmountOrDetails: '$45 / hr',
      durationMonths: 6,
      applicationDeadline: '2026-04-15',
      createdAt: '2026-09-18T10:00:00.000Z',
      matchesVerified: 62,
      status: 'Active • Accepting',
    },
    {
      jobId: 'job-02',
      jobTitle: 'Associate Machine Learning Engineer',
      targetDomain: 'AI Infrastructure • Class of 2025',
      jobDescriptionSummary: 'Train and deploy deep learning models and agentic workflows.',
      internshipType: ['Full-time'],
      locationCity: 'Austin, TX',
      minimumGPA: 3.6,
      allowedYearsOfStudy: [4],
      mandatorySkills: ['PyTorch', 'CUDA', 'Python'],
      niceToHaveSkills: ['FastAPI', 'LangChain'],
      preferredDegreePrograms: ['M.S. Machine Learning', 'B.S. CS'],
      stipendOffered: true,
      stipendAmountOrDetails: '$55 / hr',
      durationMonths: 6,
      applicationDeadline: '2026-03-31',
      createdAt: '2026-09-17T10:00:00.000Z',
      matchesVerified: 48,
      status: 'Active • Accepting',
    },
    {
      jobId: 'job-03',
      jobTitle: 'Hardware Systems Intern',
      targetDomain: 'Embedded Firmware • Summer 2026',
      jobDescriptionSummary: 'Firmware development on ARM Cortex microcontrollers.',
      internshipType: ['Full-time', 'On-site'],
      locationCity: 'Boston, MA',
      minimumGPA: 3.4,
      allowedYearsOfStudy: [3, 4],
      mandatorySkills: ['C++', 'Verilog', 'RTOS'],
      niceToHaveSkills: ['Linux', 'SPI/I2C'],
      preferredDegreePrograms: ['B.S. Electrical & Computer Eng'],
      stipendOffered: true,
      stipendAmountOrDetails: '$40 / hr',
      durationMonths: 4,
      applicationDeadline: '2026-05-01',
      createdAt: '2026-09-16T10:00:00.000Z',
      matchesVerified: 76,
      status: 'Shortlist Review',
    },
  ],
  shortlistedCandidates: [
    {
      id: 'cand-1',
      initials: 'KP',
      fullName: 'Kasun Perera',
      university: 'SLIIT',
      degree: 'B.Sc. (Hons) Software Engineering',
      batch: 'Class of 2026',
      gpa: 3.92,
      matchedOpening: 'Backend Engineering Co-op',
      matchScore: 98,
      competencies: ['Python', 'Go', 'PostgreSQL', 'Docker'],
      status: 'Shortlisted',
      statusColor: 'blue',
    },
    {
      id: 'cand-2',
      initials: 'CJ',
      fullName: 'Chamodi Jayawardena',
      university: 'University of Moratuwa',
      degree: 'B.Sc. (Hons) Computer Science & Engineering',
      batch: 'Class of 2025',
      gpa: 3.95,
      matchedOpening: 'Associate Machine Learning Engineer',
      matchScore: 97,
      competencies: ['PyTorch', 'Python', 'CUDA', 'FastAPI'],
      status: 'Pre-screen Cleared',
      statusColor: 'emerald',
    },
    {
      id: 'cand-3',
      initials: 'TS',
      fullName: 'Thisara Senanayake',
      university: 'UCSC',
      degree: 'B.Sc. (Hons) Computer Science',
      batch: 'Class of 2026',
      gpa: 3.84,
      matchedOpening: 'Hardware Systems Intern',
      matchScore: 95,
      competencies: ['C++', 'RTOS', 'Verilog', 'Embedded Systems'],
      status: 'Interview Confirmed',
      statusColor: 'purple',
    },
    {
      id: 'cand-4',
      initials: 'AW',
      fullName: 'Anuki Wijesinghe',
      university: 'University of Peradeniya',
      degree: 'B.Sc. (Hons) Electrical & Electronic Engineering',
      batch: 'Class of 2026',
      gpa: 3.88,
      matchedOpening: 'Backend Engineering Co-op',
      matchScore: 94,
      competencies: ['Python', 'Distributed Systems', 'PostgreSQL'],
      status: 'Shortlisted',
      statusColor: 'blue',
    },
    {
      id: 'cand-5',
      initials: 'DF',
      fullName: 'Dilan Fernando',
      university: 'IIT Sri Lanka',
      degree: 'B.Eng. (Hons) Software Engineering',
      batch: 'Class of 2025',
      gpa: 3.79,
      matchedOpening: 'Associate Machine Learning Engineer',
      matchScore: 93,
      competencies: ['PyTorch', 'LangChain', 'Vector DBs', 'Python'],
      status: 'Pre-screen Cleared',
      statusColor: 'emerald',
    },
    {
      id: 'cand-6',
      initials: 'RG',
      fullName: 'Rashmi Gunasekara',
      university: 'University of Sri Jayewardenepura',
      degree: 'B.Sc. (Hons) Information Technology',
      batch: 'Class of 2026',
      gpa: 3.76,
      matchedOpening: 'Hardware Systems Intern',
      matchScore: 91,
      competencies: ['Linux', 'C++', 'UART/SPI', 'ARM Cortex'],
      status: 'Shortlisted',
      statusColor: 'blue',
    },
    {
      id: 'cand-7',
      initials: 'KB',
      fullName: 'Kavindu Bandara',
      university: 'University of Kelaniya',
      degree: 'B.Sc. (Hons) Software Engineering',
      batch: 'Class of 2025',
      gpa: 3.87,
      matchedOpening: 'Backend Engineering Co-op',
      matchScore: 96,
      competencies: ['Go', 'Docker', 'Kubernetes', 'gRPC'],
      status: 'Interview Confirmed',
      statusColor: 'purple',
    },
    {
      id: 'cand-8',
      initials: 'SS',
      fullName: 'Sanduni Silva',
      university: 'NSBM',
      degree: 'B.Sc. (Hons) Computer Science',
      batch: 'Class of 2026',
      gpa: 3.71,
      matchedOpening: 'Associate Machine Learning Engineer',
      matchScore: 92,
      competencies: ['Python', 'FastAPI', 'SQL', 'Pandas'],
      status: 'Shortlisted',
      statusColor: 'blue',
    },
    {
      id: 'cand-9',
      initials: 'PD',
      fullName: 'Praveen De Silva',
      university: 'SLIIT',
      degree: 'B.Sc. (Hons) Information Technology',
      batch: 'Class of 2025',
      gpa: 3.91,
      matchedOpening: 'Backend Engineering Co-op',
      matchScore: 97,
      competencies: ['Python', 'Microservices', 'PostgreSQL', 'Redis'],
      status: 'Pre-screen Cleared',
      statusColor: 'emerald',
    },
    {
      id: 'cand-10',
      initials: 'NW',
      fullName: 'Nimasha Wickramasinghe',
      university: 'University of Moratuwa',
      degree: 'B.Sc. (Hons) Electronic & Telecommunication Eng',
      batch: 'Class of 2026',
      gpa: 3.96,
      matchedOpening: 'Hardware Systems Intern',
      matchScore: 99,
      competencies: ['C++', 'RTOS', 'Firmware', 'Verilog'],
      status: 'Interview Confirmed',
      statusColor: 'purple',
    },
    {
      id: 'cand-11',
      initials: 'SA',
      fullName: 'Sachintha Alwis',
      university: 'UCSC',
      degree: 'B.Sc. (Hons) Software Engineering',
      batch: 'Class of 2026',
      gpa: 3.82,
      matchedOpening: 'Backend Engineering Co-op',
      matchScore: 95,
      competencies: ['Go', 'PostgreSQL', 'Docker', 'AWS'],
      status: 'Shortlisted',
      statusColor: 'blue',
    },
    {
      id: 'cand-12',
      initials: 'HM',
      fullName: 'Hiruni Mendis',
      university: 'University of Peradeniya',
      degree: 'B.Sc. (Hons) Computer Engineering',
      batch: 'Class of 2025',
      gpa: 3.89,
      matchedOpening: 'Associate Machine Learning Engineer',
      matchScore: 96,
      competencies: ['PyTorch', 'Python', 'Computer Vision', 'TensorFlow'],
      status: 'Pre-screen Cleared',
      statusColor: 'emerald',
    },
  ],
};

export const companyService = {
  async getDashboardData(email?: string): Promise<CompanyDashboardData> {
    const targetEmail = email?.trim().toLowerCase() || 'virtusa@company.com';

    try {
      const url = `${API_BASE}/company/profile?email=${encodeURIComponent(targetEmail)}`;
      const res = await fetch(url);
      if (res.ok) {
        const data = await res.json();
        return data as CompanyDashboardData;
      }
    } catch {
      // Backend offline fallback
    }

    // Dynamic fallback customized with known company names if offline
    let derivedName = 'Virtusa Corporation';
    if (targetEmail.includes('pasi')) derivedName = 'Pasi Tech Global';
    if (targetEmail.includes('acme')) derivedName = 'Acme Global Technologies Inc.';

    return {
      ...DEFAULT_DASHBOARD_DATA,
      companyName: derivedName,
      contactPersonEmail: targetEmail,
      orgCode: derivedName.substring(0, 3).toUpperCase() + '-8821',
    };
  },

  async deleteJob(jobId: string): Promise<boolean> {
    try {
      const url = `${API_BASE}/company/jobs/${jobId}`;
      const res = await fetch(url, { method: 'DELETE' });
      return res.ok;
    } catch {
      return false;
    }
  },
};
